---
galaxy_info:
  author: yeasy@github
  description: An ansible role for a typical web server
  company: yeasy@github
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
    - web
    - web:nginx
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
