---
- name: check pip
  command: which pip
  register: which_pip
  ignore_errors: true
  changed_when: false

- name: Get Install pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/home/{{ ansible_ssh_user }}/get-pip.py
  when: which_pip | failed

- name: Install pip
  shell: python /home/{{ ansible_ssh_user }}/get-pip.py
  when: which_pip | failed

- name: Install docker-py
  pip: name=docker-py version=1.1.0 state=present
