---
- name: create a new user on the listed hosts
  hosts: all
  become: yes
  become_method: sudo
  pre_tasks:
    - shell: echo 'creating a new user'
  tasks:
    - name: Add the PVtest  user testing
      shell: useradd -u 2004 -s /bin/bash -c "PV Test3" pvtest3
# Differnt ways to create the user
#    - name: Add the user 'pvtest' with a specific uid and a primary group of 'admin'
#      group:
#        name: pvtest2
#        gid: 2003
#      user:
#        name: pvtest2
#        comment: PV Test2
#        uid: 2003
#        group: pvtest2
    - name: delete the PVtest1  user testing
      shell: userdel -r pvtest1
